### ISSUE TITLE
[Bug]: Error on install.py (ModuleNotFoundError: No module named 'launch')

### ISSUE THREAD

**Issue by shsotoudegan** [Mikubill/sd-webui-controlnet#2836]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I am deploying A1111 on replicate.com with cog
i was clone ControlNet repository in extentions directory of A1111.
other extentions are installed except ControlNet

### Steps to reproduce the problem

1. put `git clone https://github.com/Mikubill/sd-webui-controlnet.git /stable-diffusion-webui/extensions/sd-webui-controlnet` on cog.yam; build -> run
2. run `cog push` for push on replicate.com
3. get this error:
`
#24 14.40 Installing requirements
#24 49.46 *** Error running install.py for extension /stable-diffusion-webui/extensions/sd-webui-controlnet.
#24 49.46 *** Command: "/root/.pyenv/versions/3.10.12/bin/python" "/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py"
#24 49.46 *** Error code: 1
#24 49.46 *** stderr: Traceback (most recent call last):
#24 49.46 ***   File "/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py", line 1, in <module>
#24 49.46 ***     import launch
#24 49.46 *** ModuleNotFoundError: No module named 'launch'
`

### What should have happened?

should this install on A1111

### Commit where the problem happens

webui: last
controlnet: last

### Command Line Arguments

```Shell
cog push
```

### List of enabled extensions

adetailer

### Console logs

```Shell
#24 14.40 Installing requirements
#24 49.46 *** Error running install.py for extension /stable-diffusion-webui/extensions/sd-webui-controlnet.
#24 49.46 *** Command: "/root/.pyenv/versions/3.10.12/bin/python" "/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py"
#24 49.46 *** Error code: 1
#24 49.46 *** stderr: Traceback (most recent call last):
#24 49.46 ***   File "/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py", line 1, in <module>
#24 49.46 ***     import launch
#24 49.46 *** ModuleNotFoundError: No module named 'launch'
```

### Additional information

cog.yaml (forked from https://github.com/speshiou/cog-sd-webui)
```yaml
# Configuration for Cog ⚙️
# Reference: https://github.com/replicate/cog/blob/main/docs/yaml.md

build:
  # set to true if your model requires a GPU
  gpu: true
  cuda: "11.8"

  # a list of ubuntu apt packages to install
  system_packages:
    - "git"
    - "wget"
    - "libgl1"

  # python version in the form '3.11' or '3.11.4'
  python_version: "3.10.12"

  # a list of packages in the format <package-name>==<version>
  python_packages:
    - "torch==2.0.1"
    - "torchvision==0.15.2"
    - "xformers==0.0.20"

  # commands run after the environment is setup
  # - git clone https://github.com/speshiou/cog-sd-webui /cog-sd-webui
  run:
    - git clone --branch v1.9.3 https://github.com/AUTOMATIC1111/stable-diffusion-webui /stable-diffusion-webui
    - git clone https://github.com/Bing-su/adetailer.git /stable-diffusion-webui/extensions/adetailer
    - git clone https://github.com/Mikubill/sd-webui-controlnet.git /stable-diffusion-webui/extensions/sd-webui-controlnet
    - wget --content-disposition -P /stable-diffusion-webui/embeddings "https://huggingface.co/datasets/gsdf/EasyNegative/resolve/main/EasyNegative.safetensors?download=true"
    - python ./init_env.py --skip-torch-cuda-test

# predict.py defines how predictions are run on your model
predict: "predict.py:Predictor"
```
